name: 'May Day! Drag to the Rescue!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9088514305185527
title: Drag to the Rescue
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#fd002f'
    - '#fc7a00'
    - '#7c86aa'
  brandStrength: 0.25
  lightness: 0.2928939419798553
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
